theme: "hugo-PaperMod"
baseURL: https://reviseandsubmit.github.io
title: Revise and Submit

markup:
  goldmark:
    renderer:
      unsafe: true
      
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
permalinks:
  post: /:year/:month/:day/:slug/
      
enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true

minify:
  disableXML: true

languages:
    en:
        languageName: "English"
        weight: 1
        menu:
            main:
                - name: About
                  url: about/
                - name: Search
                  url: search/
                  weight: 10
                - name: Tags
                  url: tags/
                  weight: 10
                - name: Categories
                  url: categories/
                  weight: 10
          
                
params:  
  profilemode:
        enabled: true
        imageURL: "Revise_And_Submit_Logo_v03.png"
        imageWidth: 160 # custom size
        imageHeight: 160 # custom size
  socialIcons:
      - name: twitter
        url: https://twitter.com/ReviseAndSubmit
      - name: RsS
        url: index.xml  
      - name: github
        url: https://github.com/ReviseAndSubmit
      - name: email
        url: "reviseandsubmit@gmail.com"

outputs:
    home:
        - HTML
        - RSS
        - JSON



